# Generated by Django 4.2.7 on 2024-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_talent_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_vector',
            field=models.JSONField(blank=True, help_text='Stored job vector for ML', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='similar_jobs',
            field=models.ManyToManyField(blank=True, help_text='Similar jobs based on ML', to='job_talent_api.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_keywords',
            field=models.TextField(blank=True, help_text='Keywords extracted from skills'),
        ),
        migrations.AddField(
            model_name='skill',
            name='aliases',
            field=models.JSONField(default=list, help_text='Alternative names for this skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('domain', 'Domain Knowledge'), ('tools', 'Tools'), ('other', 'Other')], default='technical', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Related skills', to='job_talent_api.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_vector',
            field=models.JSONField(blank=True, help_text='Stored skill vector for ML', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='career_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Expert Level', 'Expert Level')], default='Entry Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
