# Generated by Django 4.2.7 on 2024-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_talent_api', '0002_remove_job_salary_max_remove_job_salary_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.CharField(choices=[('Day shift', 'Day shift'), ('Night shift', 'Night shift'), ('Rotating shift', 'Rotating shift'), ('Flexible', 'Flexible')], default='Day shift', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
